authsApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.login,name='login'),
    url(r'logme/',views.logme,name='logme'),
    url(r'logout/',views.logout,name='logout'),
    ]

jobs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'keywords/',views.home,name='home'),
	url(r'keyword/$',views.add_key,name='keyword'),
	url(r'all/$',views.jobs,name='jobs'),
	# url(r'jobFilter/(?P<idd>\w+)/$', views.jobFilter, name='jobFilter'),
	url(r'jobFilter/$', views.jobFilter, name='jobFilter'),
	

	url(r'crawl-jobs/$',views.crawl_jobs,name='crawl_jobs'),
	url(r'sync-jobs/$',views.sync_jobs_indeed,name='sync_jobs_indeed'),
	url(r'slack-channels/$',views.slackchaneels,name='slackchaneels'),
	

    ]

myproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/',  include(admin.site.urls)),
    url(r'^jobs/', include('jobs.urls',namespace='jobs')),
    url(r'^mails/',include('mails.urls',namespace='mails')),
    url(r'^',include('authsApp.urls',namespace='authsApp')),
    
]

authsApp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class UserProfile(models.Model):
# model to store Users
	user 				= models.OneToOneField(User)
	

	def __str__(self):
		return self.user.username

authsApp/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse ,HttpResponseRedirect
from django.views.generic import TemplateView ,DetailView
from django.db.models import Q
from myproject import settings
from django.views.generic import FormView, RedirectView
from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView


# class LoginView(TemplateView):
# 	template_name = "loginn.html"

def login(request):
# After successful login ,user will be redirect to home page
	return HttpResponseRedirect(reverse('jobs:home'))



def logme(request):
# After method to check valid/registred user
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username,password=password)
		if user is not None:
			if user.is_active:
				auth_login(request,user)
				return HttpResponseRedirect(reverse('jobs:home'))
			else:
				return HttpResponse('You are not Valid')
		else:
			return HttpResponse('Login Again with valid ID and Password')
	return HttpResponse('Login Again with valid ID and Password!!')


def logout(request):
# A method to handle logout
	auth_logout(request)
	return render (request,'loginn.html',{})



# login 					= LoginView.as_view()
	
	

authsApp/templates/loginn.html
<!DOCTYPE html>
<html lang="en">
 
<head>
    <title>APP</title>
 
 
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
 
    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
 
 
</head>
 
<body>
 
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" action="{% url 'authsApp:logme' %}" method="post">
                        {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" name="username" placeholder="Username" type="username" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" name="password" placeholder="Password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                 <div>
                                     <button class="btn btn-default submit">Log in </button>
                            </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
 
</html>