authsApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.login,name='login'),
    url(r'logme/',views.logme,name='logme'),
    url(r'logout/',views.logout,name='logout'),
    ]

jobs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'keywords/',views.home,name='home'),
	url(r'keyword/$',views.add_key,name='keyword'),
	url(r'all/$',views.jobs,name='jobs'),
	# url(r'jobFilter/(?P<idd>\w+)/$', views.jobFilter, name='jobFilter'),
	url(r'jobFilter/$', views.jobFilter, name='jobFilter'),
	

	url(r'crawl-jobs/$',views.crawl_jobs,name='crawl_jobs'),
	url(r'sync-jobs/$',views.sync_jobs_indeed,name='sync_jobs_indeed'),
	url(r'slack-channels/$',views.slackchaneels,name='slackchaneels'),
	

    ]

myproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/',  include(admin.site.urls)),
    url(r'^jobs/', include('jobs.urls',namespace='jobs')),
    url(r'^mails/',include('mails.urls',namespace='mails')),
    url(r'^',include('authsApp.urls',namespace='authsApp')),
    
]

jobs/models.py
from __future__ import unicode_literals
from django.db import models
import datetime
from django.core.validators import URLValidator
from mails.models import *

# Create your models here.




class portal(models.Model):
# model to store Portal
	portal_name			= models.CharField(max_length=100)
	portal_link 		= models.TextField(validators=[URLValidator()])
	last_updated		= models.DateTimeField(null=True,auto_now_add=True)

	def __str__(self):
		return self.portal_name

class allUsStates(models.Model):
# model to store all US states
	statename = models.CharField(max_length=500)
	statekey = models.CharField(max_length=400)


sendonSlack =(
				('0','0 '),
				('1','1'),
     		) 

ChannelType = (
				('mail','mail'),
				('job','job'),

	)

class DenywordsList(models.Model):
	denywords 			= models.CharField(max_length=1000,verbose_name='Deny Keywords  (Eg: Contract,W2,Fulltime )')

	def __str__(self):
		return self.denywords

class slack_channel(models.Model):
# model to store various Slack Channels
	slack_name   		= models.CharField(max_length=100,verbose_name = 'Slack Channel Name #')
	channel_ID			= models.CharField(max_length=500,verbose_name = 'Slack Webhooks ID')
	channeltype 		= models.CharField(max_length=50,choices=ChannelType)
	last_updated		= models.DateTimeField(null=True,auto_now_add=True)

 
	def __str__(self):
		return self.slack_name


class keyword_search(models.Model):
	keyword_name		= models.CharField(max_length=50,unique=True)
	last_updated		= models.DateTimeField(null=True,auto_now_add=True)
	slack_channel_con 	= models.ForeignKey(slack_channel)
	deny_filters 		= models.ForeignKey(DenywordsList,default='')


	def __str__(self):
		return self.keyword_name




class job(models.Model):
	job_title 			= models.CharField(max_length=100)
	job_discription     = models.CharField(max_length=4000)
	company_name 		= models.CharField(max_length=50,default='',null=True,blank=True)
	company_email		= models.EmailField(max_length=100,default='',null=True,blank=True)
	portal_id			= models.ForeignKey(portal)
	send_on_slack		= models.CharField(max_length=20,choices=sendonSlack)
	keyword 			= models.ForeignKey(keyword_search)
	last_updated		= models.CharField(max_length=400,default='')
	job_url 			= models.CharField(max_length=1000)
	state 				= models.ForeignKey(allUsStates)

	def __str__(self):
		return self.job_title

jobs/forms.py
from django import forms
from datetime import date
import warnings
from mails.models import *
from .models import * 
from django.core import validators


# class add_keyword(forms.ModelForm):
# 	class Meta:
# 		model=keyword_search
# 		fields=('keyword_name','discription',)

# 	def clean_key(self):
# 		print(self.cleaned_data)
# 		keyword_name      = self.cleaned_data.get('keyword_name')
# 		print(keyword_name)

# 		keyword_qs = keyword_search.objects.filter(Keyword_name=keyword_name)
# 		if  keyword_qs.exists():
# 			raise forms.ValidationError("This keyword has  already been registered")
# 		else:
# 			return keyword_name

	

jobs/views.py
from django.shortcuts import render, redirect, render_to_response
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404,redirect
from mails.models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from JobSearch import getAllJobsFromIndeed
from threading import Thread

# @login_required
def home(request):
# Function to handle home page view
	keyword_list = keyword_search.objects.all()
	page = request.GET.get('page', 1)
	paginator = Paginator(keyword_list, 10)
	try:
		keywords = paginator.page(page)
	except PageNotAnInteger:
		keywords = paginator.page(1)
	except EmptyPage:
		keywords = paginator.page(paginator.num_pages)
	return render(request, 'home.html', { 'keywords': keywords })
	
# @login_required
def add_key(request):
# Function to handle adding keywords for search.
  keyword_list = keyword_search.objects.all()
  form=add_keyword(request.POST or None)
  page = request.GET.get('page', 1)
  paginator = Paginator(keyword_list, 10)
  try:
	keywords = paginator.page(page)
  except PageNotAnInteger:
		keywords = paginator.page(1)
  except EmptyPage:
		keywords = paginator.page(paginator.num_pages)
  if form.is_valid():
	# keyword_search.added_by=request.user
	data=form.cleaned_data
	form.save()
	return HttpResponseRedirect('/jobs/keywords/')
  
# @login_required
def jobs(request):
# Function to show all jobs available
	keywords=keyword_search.objects.all()
	jobs_list=job.objects.all()
	page = request.GET.get('page', 1)
	paginator = Paginator(jobs_list, 20)
	try:
		jobs = paginator.page(page)
	except PageNotAnInteger:
		jobs = paginator.page(1)
	except EmptyPage:
		jobs = paginator.page(paginator.num_pages)
	return render(request,"jobs.html",{'jobs':jobs,'keywords':keywords})



# def jobFilter(request,idd):
# 	data = job.objects.filter(keyword=idd)
# 	return render(request,"test.html",{'data':data})
def jobFilter(request):
# Function to filter jobs
	keywords=keyword_search.objects.all()
	jobs=job.objects.all()
	return render(request,"jobs.html",{'jobs':jobs,'keywords':keywords})



class trackThread(Thread):
# Thread created to store keyword, state name , state ID.
	def __init__(self,keyname,statename,portalid,keywordid,stateid):
		self.keyname,self.statename,self.portalid,self.keywordid,self.stateid = keyname,statename,portalid,keywordid,stateid
		super(self.__class__, self).__init__()

	def run(self):
		jobsInstance = getAllJobsFromIndeed(self.keyname,self.statename,self.portalid,self.keywordid,self.stateid)
		jobsInstance.getAllJobs()


def sync_jobs_indeed(request):
# Function created to get all jobs from indeed
	if request.method == 'POST':
		keyword = request.POST['keyword']
		portals = request.POST['portal']
		state = request.POST['state']

		keywordinsta = keyword_search.objects.get(pk=int(keyword))
		portalinsta = portal.objects.get(pk=int(portals))
		statesinsta = allUsStates.objects.get(pk=int(state))
		
		t = trackThread(str(keywordinsta.keyword_name),str(statesinsta.statename),portals,keyword,state)
		t.start()

		return HttpResponse('Crawling Started !!! ')
	else:
		return HttpResponse("IT S GET")


def crawl_jobs(request):
# Function crawls jobs on the basis of given keyword and state
	keywords = keyword_search.objects.all()
	postals = portal.objects.all()
	allstates = allUsStates.objects.all()
	return render(request,"crawljobs.html",{'portal':postals,'keywords':keywords,"allstates":allstates})

# @login_required
def slackchaneels(request):
# Function to display all Slack channels
	slackch = slack_channel.objects.all()
	return render(request,"slack_channels.html",{"slack":slackch})

jobs/templates/crawljobs.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
 
<head>
    <title>Welcome</title>
 
 
  
   
    <link href={% static 'home/jumbotron-narrow.css' %} rel="stylesheet">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
</head>
 
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">APP</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
                <li><a href="{% url 'jobs:home' %}">Keywords</a></li>
         <li><a href="{% url 'jobs:jobs' %}">Jobs</a></li>
         <li><a href="{% url 'mails:home' %}">Mails</a></li>
         <li><a href="{% url 'jobs:slackchaneels' %}">Slack Channels</a></li>


        
       
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'authsApp:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
 
    <div class="container">
        <div class="row">
              <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-16">
                    <h1 class="page-header">Start Job Crawling</h1>
                </div>
               
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-16"> 
                    <div class="panel panel-priary">
                          <div class="container">  
                                <form  action="{% url 'jobs:sync_jobs_indeed' %}" method="post">
                                  {% csrf_token %}
                                          <div class="form-group">
                                              <div class="row">

                                                      <div class="col-md-4">
                                                              <label>Select Keyword:</label>
                                                      </div>   
                                                      <div class="col-md-8">
                                                           <select name="keyword" class="form-control"> 
                                                              {% for key in keywords %}
                                                                <option value="{{key.id}}">{{key}}</option>
                                                              {% endfor %}
                                                            </select>

                                                      </div>   

                                              </div>
                                          </div>
                                           <div class="form-group">
                                              <div class="row">

                                                      <div class="col-md-4">
                                                              <label>Select Portal:</label>
                                                      </div>   
                                                      <div class="col-md-8">
                                                           <select name="portal" class="form-control"> 
                                                              {% for por in portal %}
                                                                <option value="{{por.id}}">{{por}}</option>
                                                              {% endfor %}
                                                            </select>

                                                      </div>   

                                              </div>
                                          </div>
                                          <div class="form-group">
                                              <div class="row">

                                                      <div class="col-md-4">
                                                              <label>Enter State:</label>
                                                      </div>   
                                                      <div class="col-md-8">
                                                          <select name="state" class="form-control"> 
                                                              {% for state in allstates %}
                                                                <option value="{{state.id}}">{{state.statename}}, {{state.statekey}}</option>
                                                              {% endfor %}
                                                            </select>
                                                            
                                                      </div>   

                                              </div>
                                          </div>
                                            <div class="form-group">
                                              <div class="row">

                                                      <div class="col-md-4">
                                                             <input type="submit" class="btn btn-info btn-lg" value="Start">
                                                      </div>   
                                                      <div class="col-md-8">
                                                      </div>   

                                              </div>
                                          </div>
                                 </form>
                            </div>
                    </div>
                    
                </div>
               
             </div>
        </div>     
    </div>
        
</body>
 
</html>

jobs/templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
 
<head>
    <title>Welcome</title>
 
 
  
   
    <link href={% static 'home/jumbotron-narrow.css' %} rel="stylesheet">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
</head>
 
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">APP</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
       
               <li><a href="{% url 'jobs:home' %}">Keywords</a></li>
         <li><a href="{% url 'jobs:jobs' %}">Jobs</a></li>
         <li><a href="{% url 'mails:home' %}">Mails</a></li>
         <li><a href="{% url 'jobs:slackchaneels' %}">Slack Channels</a></li>

        
       
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
    <li>
      <!-- <a href="{% url 'authsApp:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a> -->

    </li>
      </ul>
    </div>
  </div>
</nav>
 
    <div class="container">
        <div class="row">
              <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-16">
                    <h1 class="page-header">Keywords</h1>
                </div>
                <div class="container" style="margin-left:74%">
                           
                              <br/>
                            <!-- Modal -->
                            <div class="modal fade" id="myModal" role="dialog">
                              <div class="modal-dialog">
                              
                                <!-- Modal content-->
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Enter New Keyword here....!!!</h4>
                                  </div>

                                  <div class="modal-body">
                                      <form method="POST" action="{% url 'jobs:keyword' %}"> {% csrf_token %}
                                          <table>
                                          {% if forms.errors %}
                                            <p>
                                                correct some stuff
                                            </p>
                                            {% endif %}
                                            <tr>
                                              <td>{{form}}</td>
                                            </tr>

                                            <tr>
                                              <td> </td>
                                              <td><input type="submit" value="SAVE" /></td>
                                            </tr>
                                          </table>
                                          
                                     </form>

                               

                                </div> 
                              </div>
                            </div>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-16"> 
                    <div class="panel panel-primary">
                        <div class="panel-heading">&nbsp;&nbsp;ADDED  KEYWORDS    </div>
                          <div class="container">  
                              <table class="table table-striped">
                                <thead>
                                  <tr>
                                    <th>ID</th>
                                    <th>KEYWORD</th>
                                    <th>Associated with(Slack Channel)</th>
                                    <th>DATE ADDED</th>
                                  </tr>
                                </thead>
                                <tbody>
                                {% for i in keywords %}
                                  <tr>
                                    <td>{{i.id}}</td>
                                    <td>{{i.keyword_name}}</td>
                                    <td>{{i.slack_channel_con}}</td>
                                    <td>{{i.last_updated}}</td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
{% if keywords.has_other_pages %}
  <ul class="pagination">
    {% if keywords.has_previous %}
      <li><a href="?page={{ keywords.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in keywords.paginator.page_range %}
      {% if keywords.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if keywords.has_next %}
      <li><a href="?page={{ keywords.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
                            </div>
                           </div>
                        <div class="panel-body">
                           
                    
                        <div class="panel-footer">
                       
                        </div>
                           
                        </div>
                    
                    </div>
                    
                </div>
               
             </div>
        </div>     
    </div>
        
</body>
 
</html>

jobs/templates/jobs.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
 
<head>
    <title>Welcome</title>
 
 
   
    <link href={% static 'home/jumbotron-narrow.css' %} rel="stylesheet">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  
</head>
 
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">APP</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
       
         <li><a href="{% url 'jobs:home' %}">Keywords</a></li>
         <li><a href="{% url 'jobs:jobs' %}">Jobs</a></li>
         <li><a href="{% url 'mails:home' %}">Mails</a></li>
         <li><a href="{% url 'jobs:slackchaneels' %}">Slack Channels</a></li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
    <li>
      <!-- <a href="{% url 'authsApp:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a> -->
    </li>
      </ul>
    </div>
  </div>
</nav>
 
    <div class="container-fluid">
        <div class="row">
              <div id="page-wrapper">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="page-header">&nbsp;&nbsp;Jobs</h1>
                </div>
                <div class="col-md-4">
                      <!-- <a href="{% url 'jobs:crawl_jobs' %}" class="btn btn-info">Crawl Jobs</a> -->
                </div>

                   <!--  <form action="{% url 'jobs:jobFilter' %}" method="GET">

                        <div class="row">
                                <div class="col-md-6">
                                       <select class="form-control" name="keyword">
                                          {% for i in keywords %}
                                          <option value="{{i.id}}">{{i.keyword_name}}</option>
                                          {% endfor %}
                                        </select>

                                </div>
                                <div class="col-md-6">
                                   <button type="submit" class="btn btn-info">Load Jobs</button>
                                </div>
                        </div>
                    </form> -->
               
                <!-- /.col-lg-12 -->
                  <br/>






            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12"> 
                    <div class="panel panel-primary">
                          <div class="container-fluid">  
                              <table class="table table-striped">
                                <thead>
                                  <tr>
                                    <th>#</th>
                                    <th>Title</th>
                                    <th>Description</th>
                                    <th>Company name</th>
                                    <th>Location</th>
                                    <th>Portal</th>
                                    <th>Keyword</th>


                                  </tr>
                                </thead>
                                <tbody>
                                {% for i in jobs %}
                                  <tr>
                                    <td>{{i.id}}</td>
                                    <td>{{i.job_title}}</td>
                                    <td>{{i.job_discription}}</td>
                                     <td>{{i.company_name}}</td>
                                     <td>{{i.state.statename}}, {{i.state.statekey}}</td>
                                     <td>{{i.portal_id}}</td>
                                     <td>{{i.keyword}}</td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
{% if jobs.has_other_pages %}
  <ul class="pagination">
    {% if jobs.has_previous %}
      <li><a href="?page={{ jobs.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in jobs.paginator.page_range %}
      {% if jobs.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if jobs.has_next %}
      <li><a href="?page={{ jobs.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
                            </div>
                           </div>
                        <div class="panel-body">
                           
                    
                        <div class="panel-footer">
                       
                        </div>
                           
                        </div>
                    
                    </div>
                    
                </div>
               
             </div>
        </div>     
    </div>
        
</body>
 
</html>

jobs/templates/slack_channels.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
 
<head>
    <title>Welcome</title>
 
 
   
    <link href={% static 'home/jumbotron-narrow.css' %} rel="stylesheet">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  
</head>
 
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">APP</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
       
         <li><a href="{% url 'jobs:home' %}">Keywords</a></li>
         <li><a href="{% url 'jobs:jobs' %}">Jobs</a></li>
         <li><a href="{% url 'mails:home' %}">Mails</a></li>
         <li><a href="{% url 'jobs:slackchaneels' %}">Slack Channels</a></li>

        
      </ul>
      <ul class="nav navbar-nav navbar-right">
    <li>

      <!-- <a href="{% url 'authsApp:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a> -->
    </li>
      </ul>
    </div>
  </div>
</nav>
 
    <div class="container-fluid">
        <div class="row">
              <div id="page-wrapper">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="page-header">&nbsp;&nbsp;Slack Channels</h1>
                </div>
                <div class="col-md-4">
                </div>

                
                  <br/>






            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12"> 
                    <div class="panel panel-primary">
                          <div class="container-fluid">  
                              <table class="table table-striped">
                                <thead>
                                  <tr>
                                    <th>#</th>
                                    <th>Channel Name</th>
                                    <th>Channel Type</th>
                                    <th>Slack incomming Webhooks id <a href="http://slack.com/apps/search?q=webhooks" target="_blank">Get webhooks id here</a>  </th>

                                  </tr>
                                </thead>
                                <tbody>
                                  {% for ch in slack %}
                                  <tr>
                                      <td></td>
                                      <td>{{ch.slack_name}}</td>
                                      <td>{{ch.channeltype}}</td>
                                      <td>{{ch.channel_ID}}</td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>

                            </div>
                           </div>
                        <div class="panel-body">
                           
                    
                        <div class="panel-footer">
                       
                        </div>
                           
                        </div>
                    
                    </div>
                    
                </div>
               
             </div>
        </div>     
    </div>
        
</body>
 
</html>